RedHatInsights/pdf-generator

CONTRIBUTING.md
browser/index.ts
package-lock.json
package.json
server/data-access/automation-analytics/aapScript.js
server/data-access/automation-analytics/index.ts
server/data-access/call-service.ts
server/data-access/complianceDescriptor/index.ts
server/data-access/demo-data/index.ts
server/data-access/demoDescriptor/index.ts
server/data-access/index.ts
server/data-access/service-names.ts
server/index.tsx
server/render-template/index.tsx
server/types.ts
templates/automation-analytics/App.tsx
templates/index.tsx

jira: https://issues.redhat.com/browse/RHCLOUD-18445
We can't test these changes until we are on the stage env
- create APIDescriptor type to construct API calls
- enforce `mock` functions for local development; it is impossible to do internal cluster call locally
- use `enum` to define available services
- use `pdf-generator` service name in URL instead of ansible

Implement base for API-API communication

---

CONTRIBUTING.md
server/data-access/advisorDescriptor/index.ts
server/data-access/call-service.ts
server/data-access/index.ts
server/data-access/service-names.ts
templates/advisor/Components/top-recommendations.tsx
templates/advisor/Template.tsx
templates/index.tsx

https://issues.redhat.com/browse/RHCLOUD-18353

Advisor report initial commit

---

browser/helpers.js
browser/index.ts
server/index.tsx

With the extra query param, we can now have fat pdf's!
Addressing this Jira card

Landscape orientation option

---

deploy/clowdapp.yml
server/config/index.ts
server/data-access/call-service.ts
server/index.tsx

jirapart of: https://issues.redhat.com/browse/RHCLOUD-20639

Consume compliance from clowder

---

dashboards/grafana-dashboard-insights-crc-pdf-generator-general.configmap.yaml

jira: https://issues.redhat.com/browse/RHCLOUD-21075

Add grafana dashboard definition.

---

INTEGRATION.md
README.md
src/server/data-access/call-service.ts

jira: https://issues.redhat.com/browse/RHCLOUD-21057

Add service integration guide.

---

deploy/clowdapp.yml
src/common/config.ts
src/server/data-access/advisorDescriptor/advisorData.ts
src/server/data-access/advisorDescriptor/index.ts
src/server/data-access/complianceDescriptor/index.ts

part of: https://issues.redhat.com/browse/RHCLOUD-21558

Add advisor template data request

---

deploy/clowdapp.yml
package-lock.json
package.json
src/common/config.ts
src/common/service-names.ts
src/server/data-access/call-service.ts
src/server/data-access/index.ts
src/server/data-access/rosDescriptor/index.ts
src/server/data-access/rosDescriptor/rosData.ts
src/server/routes/routes.ts
src/templates/common/components/table-legend.tsx
src/templates/common/components/text-with-color-dot.tsx
src/templates/index.ts
src/templates/ros/executive-report/index.tsx

Feel free to start with the review, the last todo item must be done in a different repo

Ros integration

---

src/server/data-access/vulnerabilityDescriptor/index.ts
src/templates/index.ts

Addressing this [Jira Task](https://issues.redhat.com/browse/RHCLOUD-21557)

Adding api descriptor to vulnerabilities report

---

src/server/data-access/rosDescriptor/rosData.ts
src/templates/common/components/table-legend.tsx
src/templates/common/components/text-with-color-dot.tsx
src/templates/ros/Components/instances-table.tsx
src/templates/ros/executive-report/index.tsx

Migration of ROS Executive report to V2
**Jira:** https://issues.redhat.com/browse/RHIROS-861
**PDFs:** https://drive.google.com/file/d/1xuL0j6yG508oF41VurfqMIuhIiDARfb0/view?usp=share_link

RHIROS-861 ROS Executive Report V2

---

INTEGRATION.md

Fixed `getting started with EE` link in INTEGRATION.md

Updated link in INTEGRATION.md

---

deploy/clowdapp.yml

Might help with: https://issues.redhat.com/browse/RHIROS-1006

Bump memory limit.

---

INTEGRATION.md

Update INTEGRATION.md - EE documentation link

Update INTEGRATION.md - EE documentation link

---

src/server/index.ts
src/server/workers.ts

Keep alive request connection.

---

dashboards/grafana-dashboard-insights-crc-pdf-generator-general.configmap.yaml

App SRE has requested we update our threshold colors to more easily understand the data.

Update thresholds in Grafana dashboard

---

deploy/clowdapp.yml
src/common/config.ts
src/server/data-access/call-service.ts
src/server/data-access/complianceDescriptor/index.ts

This reverts commit c60aa74eda6549fbad232212834ded74427a70b8 that wrongly updates compliance clowder name.

Revert "properly build compliance clowder endpoints (#55)"

---

Dockerfile
src/browser/puppeteerWorker.ts
src/server/data-access/call-service.ts
src/server/data-access/index.ts
src/server/data-access/vulnerabilityDescriptor/index.ts
src/server/index.ts
src/server/routes/routes.ts
src/server/workers.ts

This change set should unblock teams getting OOM Killed in stage/prod. 
I ran the largest dataset (1000+ systems) we had in ephemeral a few times and was able to stay around 600 Mb. The graph below shows the yellow line as our memory limit, the green line as our memory request, and the blue line as our memory usage. We can see clear spikes and reliefs when a pdf generation stops and starts. The initial spike is from Chrome starting and idling while waiting for a new connection. After that, we can see peaks and dips as the server releases resources.

[RHCLOUD-26267] Optimize PDF generation

---

docs/openapi.json
src/browser/previewPDF.ts
src/server/routes/routes.ts

Implement OpenAPI spec for crc-pdf-generator

[RHCLOUD-26720] Create OpenAPI Spec

---

src/browser/puppeteerWorker.ts

Updates the browser and pdf operation to timeout after 60 seconds.

[RHCLOUD-26275] Bump timeout for pdfs

---

.github/workflows/test.yaml
docs/validateOpenAPI.sh
pr_check.sh

* Validates `openapi.json` file with each PR

[RHCLOUD-26720] Add GH action for openapi validation

---

src/server/data-access/rosDescriptor/rosData.ts
src/templates/ros/utils.ts

With the recent changes in adding group filter in the UI, we needed to update the option while downloading systems report. Hence I am raising this MR to fix the same.
Jira: https://issues.redhat.com/browse/RHIROS-1306

RHIROS-1306 handle group filter for system report

---

src/browser/helpers.ts
src/browser/previewPDF.ts
src/browser/puppeteerWorker.ts
src/server/cache.ts
src/server/data-access/rosDescriptor/rosLargeDataSet.json
src/server/routes/routes.ts

* Refactor caching into its own class and run for the duration of the pod
* Add input sanitization for Snyk checks
* Update timeout to match gateway
* Adds mock dataset for local debugging
These changes should fix the issues we're seeing with stacked generation calls in stage / prod.

[RHCLOUD-26275] Refactor cache mechanism

---

deploy/clowdapp.yml

* Use template var to pick bucket name dynamically

Make storage bucket name dynamic

---

package-lock.json
package.json
src/common/config.ts
src/common/kafka.ts

* Updates clowder lib to `2.2.3`
* Uses sasl and ssl detector more accurately

Update Kafka config for stage

---

fixtures/stage.json
package-lock.json
package.json
src/common/config.ts
src/common/kafka.spec.ts
src/common/kafka.ts
src/jest.setup.ts
src/unit.jest.config.js

* Assert ssl and sasl are under test

Add unit tests for kafka

---

src/common/kafka.ts

* Use a consumer group per pod to ensure each pod gets every kafka message
* Fix debug logging

[RHCLOUD-31211] Sync kafka messages across pods

---

src/common/objectStore.ts

The minio uses a different constructor for s3 than minio. We'll use that to fix the 403 issue
https://min.io/docs/minio/linux/developers/javascript/API.html#aws-s3

Use different constructor for s3

---

build_deploy.sh

Store the docker config in a new tmp dir instead of the $WORKSPACE

use temp dir for docker config

---

deploy/clowdapp.yml
package-lock.json
package.json
src/common/config.ts
src/server/routes/routes.ts

Part of: https://issues.redhat.com/browse/RHCLOUD-32573

Allow proxy agent config.

---

deploy/clowdapp.yml
src/client/bootstrap.tsx
src/common/config.ts
src/integration/endpoints.ts
src/server/render-template/index.tsx
src/server/routes/routes.ts

Part of: https://issues.redhat.com/browse/RHCLOUD-32573

Enable internal API routing.

---

src/client/bootstrap.tsx
src/common/config.ts
src/integration/endpoints.ts
src/server/routes/createInternalProxies.ts
src/server/routes/routes.ts

Part of: https://issues.redhat.com/browse/RHCLOUD-32573

Add internal API proxies.

---

deploy/clowdapp.yml
docs/template-development.md
src/server/routes/createInternalProxies.ts

Jira: https://issues.redhat.com/browse/RHCLOUD-32762

Enable local development API host setup.

---

src/browser/clusterTask.ts
src/client/bootstrap.tsx
src/common/pdfCache.ts
src/server/render-template/index.tsx

Jira: https://issues.redhat.com/browse/RHCLOUD-32763

Enable React error handling.

---

src/server/cluster.ts
src/server/routes/routes.ts

* Cluster should not be closed after first request
* Limit retries when a queued item fails

Fix cluster restart issue

---

docs/openapi.json
package-lock.json
package.json

* Update to match all v2 endpoints
* Remove deprecated swagger validator
* Use [vacuum](https://github.com/daveshanley/vacuum) to lint API

[RHCLOUD-32873] Update OpenAPI Spec

---

src/common/pdfCache.ts
src/server/routes/routes.ts

* Ensure that a collection has contents before verification
* validate the collection before getting the full status object to return to users

[RHCLOUD-33471] Update collection validation

---

docker-compose.yml

Remove dockerhub images and swap to quay

[RHCLOUD-33854] use quay for local images

---

.tekton/pdf-generator-pull-request.yaml
.tekton/pdf-generator-push.yaml

https://issues.redhat.com/browse/RHCLOUD-30183

set up source build image

---

src/common/pdfCache.spec.ts
src/common/pdfCache.ts

* Ensure `Generated` and `Failed` are consistent
* Add extra unit testing

[RHCLOUD-33471] Update logic on complex status objects

---

Dockerfile
deploy/clowdapp.yml
package-lock.json
pr_check.sh
src/common/objectStore.ts
src/server/cluster.ts
src/server/routes/routes.ts

* Changes the resource env var pattern to match the ADR
* Updates Dockerfile for security scanner
* Limits PDF slices to 50 while we determine the aws socket issue

[RHCLOUD-34084] Trusted Resource ADR 

---

README.md
docs/onboarding.md
docs/pdf-template-development.md

Adds an overview of the high level steps to the existing documentation

Update onboarding guide for v2

---

docs/pdf-template-development.md

* Adds docs for new `frontend-components/types`
* Adds example of new type usage

[RHCLOUD-35115] Update PDF module examples to use FEC types

---

jest.config.js
package-lock.json
package.json
src/common/objectStore.ts
src/common/pdfCache.ts
src/server/routes/routes.ts
tsconfig.json

* Fixes s3 connection issue
* Merges all PDF slices upon completion instead of at download time
* Now handles > 50 slices with some performance increases

[RHCLOUD-34983] Merge pdfs before download

---

docs/creating-api-requests.md
docs/local-development-setup.md

Fixes the links in creating-api-requests doc

updated references in creating-api-requests.md

---

deploy/clowdapp.yml

https://redhat-internal.slack.com/archives/C023VGW21NU/p1738624966806419?thread_ts=1738361418.881689&cid=C023VGW21NU

Onboarding advisor - advisor-backend dependency

---

README.md

See RHCLOUD-41483 for details.

RHCLOUD-41483: Deployment timing
